<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
			<PackageReference Include="Shouldly" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Miniclip.Core.Tests\Miniclip.Core.Tests.csproj" />
		<ProjectReference Include="..\Miniclip.Simulator.Application.Commands\Miniclip.Simulator.Application.Commands.csproj" />
		<ProjectReference Include="..\Miniclip.Simulator.Domain\Miniclip.Simulator.Domain.csproj" />
	</ItemGroup>

</Project>
