<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KurrentDB.Client" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miniclip.Core.EventSourcing\Miniclip.Core.EventSourcing.csproj" />
    <ProjectReference Include="..\Miniclip.Core\Miniclip.Core.csproj" />
    <ProjectReference Include="..\Miniclip.Core.Propagation\Miniclip.Core.Propagation.csproj" />
  </ItemGroup>

</Project>
