// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miniclip.Simulator.Infrastructure.Read.Persistence;

#nullable disable

namespace Miniclip.Simulator.Infrastructure.Read.Migrations
{
    [DbContext(typeof(SimulatorReadDbContext))]
    [Migration("20260215233743_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Miniclip.Simulator.ReadModels.Models.GroupStandingsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("QualifiesForKnockout")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TeamStrength")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_GroupStandings_GroupId");

                    b.HasIndex("GroupId", "Position")
                        .HasDatabaseName("IX_GroupStandings_GroupId_Position");

                    b.HasIndex("GroupId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_GroupStandings_GroupId_TeamId");

                    b.ToTable("GroupStandings", (string)null);
                });

            modelBuilder.Entity("Miniclip.Simulator.ReadModels.Models.MatchResultModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PlayedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_MatchResults_GroupId");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchResults_MatchId");

                    b.HasIndex("GroupId", "Round")
                        .HasDatabaseName("IX_MatchResults_GroupId_Round");

                    b.HasIndex("GroupId", "HomeTeamId", "AwayTeamId")
                        .HasDatabaseName("IX_MatchResults_GroupId_Teams");

                    b.ToTable("MatchResults", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
