// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miniclip.Simulator.Infrastructure.Write.Persistence;

#nullable disable

namespace Miniclip.Simulator.Infrastructure.Write.Migrations
{
    [DbContext(typeof(SimulatorWriteDbContext))]
    partial class SimulatorWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GroupTeams", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("GroupId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("GroupTeams", (string)null);
                });

            modelBuilder.Entity("Miniclip.Simulator.Domain.Aggregates.Groups.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Miniclip.Simulator.Domain.Aggregates.Teams.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("GroupTeams", b =>
                {
                    b.HasOne("Miniclip.Simulator.Domain.Aggregates.Groups.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miniclip.Simulator.Domain.Aggregates.Teams.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Miniclip.Simulator.Domain.Aggregates.Groups.Entities.Group", b =>
                {
                    b.OwnsMany("Miniclip.Simulator.Domain.Aggregates.Groups.Entities.Match", "Matches", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("MatchId");

                            b1.Property<int>("AwayScore")
                                .HasColumnType("int");

                            b1.Property<Guid>("AwayTeamId")
                                .HasColumnType("char(36)")
                                .HasColumnName("AwayTeamId");

                            b1.Property<int>("HomeScore")
                                .HasColumnType("int");

                            b1.Property<Guid>("HomeTeamId")
                                .HasColumnType("char(36)")
                                .HasColumnName("HomeTeamId");

                            b1.Property<bool>("IsPlayed")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("Round")
                                .HasColumnType("int");

                            b1.HasKey("GroupId", "Id");

                            b1.HasIndex("AwayTeamId");

                            b1.HasIndex("HomeTeamId");

                            b1.ToTable("Matches", (string)null);

                            b1.HasOne("Miniclip.Simulator.Domain.Aggregates.Teams.Entities.Team", "AwayTeam")
                                .WithMany()
                                .HasForeignKey("AwayTeamId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("GroupId");

                            b1.HasOne("Miniclip.Simulator.Domain.Aggregates.Teams.Entities.Team", "HomeTeam")
                                .WithMany()
                                .HasForeignKey("HomeTeamId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("AwayTeam");

                            b1.Navigation("HomeTeam");
                        });

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
