<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miniclip.Core.Domain\Miniclip.Core.Domain.csproj" />
    <ProjectReference Include="..\Miniclip.Core.EventSourcing\Miniclip.Core.EventSourcing.csproj" />
    <ProjectReference Include="..\Miniclip.Core.Messaging\Miniclip.Core.Messaging.csproj" />
    <ProjectReference Include="..\Miniclip.Core.OpenTelemetry\Miniclip.Core.OpenTelemetry.csproj" />
    <ProjectReference Include="..\Miniclip.Core\Miniclip.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Publishers\" />
  </ItemGroup>

</Project>
